wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/run-all.script", "run-all.script");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/foodnstuff.script", "foodnstuff.script");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/harakiri-sushi.script", "harakiri-sushi.script");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/hong-fang-tea.script", "hong-fang-tea.script");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/joesguns.script", "joesguns.script");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/nectar-net.script", "nectar-net.script");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/neo-net.script", "neo-net.script");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/sigma-cosmetics.script", "sigma-cosmetics.script");
run('run-all.script');
