wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/run-all.script.js", "run-all.script.js");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/foodnstuff.script.js", "foodnstuff.script.js");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/harakiri-sushi.script.js", "harakiri-sushi.script.js");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/hong-fang-tea.script.js", "hong-fang-tea.script.js");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/joesguns.script.js", "joesguns.script.js");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/nectar-net.script.js", "nectar-net.script.js");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/neo-net.script.js", "neo-net.script.js");
wget("https://raw.githubusercontent.com/youngalex12/BitBurn/master/sigma-cosmetics.script.js", "sigma-cosmetics.script.js");
run('run-all.script.js');
